name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master
    paths:
      - MVVMNavigationModule/**
      - .github/workflows/ci-nuget-release.yml
  workflow_dispatch:

jobs:
  build-pack-publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: MVVMNavigationModule

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release mode
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package with version
        run: dotnet pack --configuration Release --no-build --output ./nupkg 

      - name: Publish to Personal NuGet Feed
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./**/nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key "$env:NUGET_API_KEY" --skip-duplicate
